channels:
- conda-forge
dependencies:
- python=3.12.8
- pip<=24.3.1
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - lz4==4.3.3
  - numpy==1.26.4
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.14.1
  - typing==3.7.4.3
name: mlflow-env
